Update CI pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,18 +10,23 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  build-and-deploy:
+  build-and-push:
     runs-on: ubuntu-latest
     permissions:
       contents: read
       packages: write
+    outputs:
+      image_lc: ${{ steps.image-name.outputs.image_lc }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Lowercase image name (GHCR requires it)
-        run: echo "IMAGE_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV
+        id: image-name
+        run: |
+          echo "IMAGE_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV
+          echo "image_lc=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -44,6 +49,26 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
+  security-scan:
+    runs-on: ubuntu-latest
+    needs: build-and-push
+    steps:
+      - name: Code Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Run Trivy Scan on Docker Image
+        uses: aquasecurity/trivy-action@v0.2.0
+        with:
+          image-ref: ${{ env.REGISTRY }}/${{ needs.build-and-push.outputs.image_lc }}:latest
+          format: 'table'
+          severity: 'CRITICAL'
+          exit-code: '1'
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: security-scan
+    steps:
       - name: Deploy via SSH
         uses: appleboy/ssh-action@v1
         with:
@@ -52,6 +77,26 @@ jobs:
           key:  ${{ secrets.SSH_KEY }}
           script: |
             cd /opt/astro-app
+            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
             docker compose pull
             docker compose up -d
             docker image prune -f
+  health-check:
+    runs-on: ubuntu-latest
+    needs: deploy
+    steps:
+      - name: Ping website to check if it's up
+        run: |
+          for i in {1..10}; do
+            if curl --fail --silent --show-error --location https://k1nd4sus.it/ > /dev/null; then
+              echo "Website is up!"
+              exit 0
+            else
+              echo "Website is not up yet. Retrying in 10 seconds..."
+              sleep 10
+            fi
+          done
+          echo "Website did not come up after 10 attempts. Failing the job."
+          exit 1
+
+          
